# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 654c3b9e7e48596be16d611502729fa03ee931b2f8a41fdf2ea7fd6d6dd8ef0ceff3b06096cb11a206cc62c6bb6e394406f00f1a200c42d5698a81ad1c326d81

test:
  secret_key_base: f5e14f9b8de713f19f91cb1c27b8f85abc263c8875ce08bd5a98604b45b10df3d84007ec0ad2e4ef7d48fc290267c3bba0df0f327eebd12fe126aefb13208f49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
